#!/usr/bin/env python3
"""
Generate MorrowDawn.colors and the matching colour blocks for
etc/skel/.config/kdeglobals from the single palette definition in
dawn_palette.py.

Generated rather than hand-written because the same ~9 colour groups appear
in both files; editing them by hand is how the v1.0 scheme ended up as a
name with no colour blocks behind it.
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
from dawn_palette import (  # noqa: E402
    NIGHT, HEADER, INDIGO, INDIGO_ALT, TOOLTIP,
    AMBER, CORAL, TEXT, TEXT_DIM, TEXT_ON_SUN,
    POSITIVE, NEUTRAL, NEGATIVE, VISITED, kde, report,
)

SCHEME_NAME = "MorrowDawn"


def group(bg, bg_alt, *, fg=TEXT, fg_inactive=TEXT_DIM,
          fg_active=CORAL, link=AMBER) -> dict:
    return {
        "BackgroundAlternate": kde(bg_alt),
        "BackgroundNormal": kde(bg),
        "DecorationFocus": kde(AMBER),
        "DecorationHover": kde(AMBER),
        "ForegroundActive": kde(fg_active),
        "ForegroundInactive": kde(fg_inactive),
        "ForegroundLink": kde(link),
        "ForegroundNegative": kde(NEGATIVE),
        "ForegroundNeutral": kde(NEUTRAL),
        "ForegroundNormal": kde(fg),
        "ForegroundPositive": kde(POSITIVE),
        "ForegroundVisited": kde(VISITED),
    }


COLOUR_GROUPS = {
    "Colors:Button":        group(INDIGO_ALT, TOOLTIP),
    "Colors:Complementary": group(HEADER, INDIGO),
    "Colors:Header":        group(HEADER, INDIGO),
    # Selection is the sun: a light amber field with dark text on it.
    "Colors:Selection":     group(
        AMBER, CORAL,
        fg=TEXT_ON_SUN, fg_inactive=TEXT_ON_SUN,
        fg_active=TEXT_ON_SUN, link=TEXT_ON_SUN,
    ),
    "Colors:Tooltip":       group(TOOLTIP, INDIGO_ALT),
    "Colors:View":          group(NIGHT, INDIGO),
    "Colors:Window":        group(INDIGO, INDIGO_ALT),
}

EFFECTS = {
    "ColorEffects:Disabled": {
        "Color": "56,56,56", "ColorAmount": "0", "ColorEffect": "0",
        "ContrastAmount": "0.65", "ContrastEffect": "1",
        "IntensityAmount": "0.1", "IntensityEffect": "2",
    },
    "ColorEffects:Inactive": {
        "ChangeSelectionColor": "true", "Color": "112,111,110",
        "ColorAmount": "0.025", "ColorEffect": "2",
        "ContrastAmount": "0.1", "ContrastEffect": "2",
        "Enable": "false", "IntensityAmount": "0", "IntensityEffect": "0",
    },
}


def render(sections: dict) -> str:
    out = []
    for name, keys in sections.items():
        out.append(f"[{name}]")
        for k in sorted(keys):
            out.append(f"{k}={keys[k]}")
        out.append("")
    return "\n".join(out)


def colour_scheme() -> str:
    sections = {}
    sections.update(EFFECTS)
    sections.update(COLOUR_GROUPS)
    sections["General"] = {
        "ColorScheme": SCHEME_NAME,
        "Name": SCHEME_NAME,
        "shadeSortColumn": "true",
    }
    sections["KDE"] = {"contrast": "4"}
    header = (
        "# MorrowOS \"Dawn\" colour scheme\n"
        "# GENERATED by tools/make_colorscheme.py from tools/dawn_palette.py\n"
        "# Edit the palette, not this file.\n"
        "# Every foreground/background pair here passes WCAG AA;\n"
        "# run `python3 tools/dawn_palette.py` to re-check.\n\n"
    )
    return header + render(sections)


def kdeglobals() -> str:
    """Colour blocks plus the non-colour defaults skel needs."""
    sections = {}
    sections.update(EFFECTS)
    sections.update(COLOUR_GROUPS)
    body = render(sections)
    tail = (
        f"[General]\n"
        f"ColorScheme={SCHEME_NAME}\n"
        f"Name={SCHEME_NAME}\n"
        f"shadeSortColumn=true\n"
        f"\n"
        f"[Icons]\n"
        f"Theme=Papirus-Dark\n"
        f"\n"
        f"[KDE]\n"
        f"contrast=4\n"
        f"widgetStyle=Breeze\n"
        f"SingleClick=false\n"
    )
    header = (
        "# GENERATED by tools/make_colorscheme.py — edit the palette instead.\n\n"
    )
    return header + body + tail


if __name__ == "__main__":
    root = Path(__file__).resolve().parent.parent
    if report():
        sys.exit("palette fails contrast check — refusing to generate")

    scheme = root / "usr/share/color-schemes" / f"{SCHEME_NAME}.colors"
    scheme.write_text(colour_scheme())
    print(f"\nwrote {scheme.relative_to(root)}")

    skel = root / "etc/skel/.config/kdeglobals"
    skel.write_text(kdeglobals())
    print(f"wrote {skel.relative_to(root)}")

    old = root / "usr/share/color-schemes/MorrowDark.colors"
    if old.exists():
        old.unlink()
        print(f"removed {old.relative_to(root)} (superseded by {SCHEME_NAME})")
